version: "3"
services:

  api:
    build:
      context: .
    #      dockerfile: Dockerfile
    container_name: pg-api
    ports:
      - "80:80"
    volumes:
      - ../src/:/api/
      - ./default.conf:/etc/apache2/sites-available/000-default.conf
